### ISSUE TITLE
Cannot read property '$meta' of undefined

### ISSUE THREAD

**Issue by muyaedward** [TiagoDanin/Nuxt-SEO#7]
I am getting this error `Cannot read property '$meta' of undefined`. I am using nuxtjs 2.8.*

`if (Vue.prototype.$meta) {
      if (Vue.prototype.$nuxt && Vue.prototype.$nuxt.$options && Vue.prototype.$nuxt.$options.head) {
        Vue.prototype.$nuxt.$options.head = ctx.app.head;
      }
    }`

**Comment by TiagoDanin** [comment]
No problems detected in tests with Nuxt [^2.8.1](https://github.com/TiagoDanin/Nuxt-SEO/pull/5/checks) and [^2.8.0](https://github.com/TiagoDanin/Nuxt-SEO/pull/3/checks).

Could you upload your `package.json` and `nuxt.config.js` ?

**Comment by ziaenezhad** [comment]
The same issue on nuxt `2.9.*`

**Comment by TiagoDanin** [comment]
> The same issue on nuxt `2.9.*`

@sajjad-shirazy Could you upload your package.json, nuxt.config.js and yarn.lock ?
