### ISSUE TITLE
Meta tags doesn't update on client side page change, used nuxt-link

### ISSUE THREAD

**Issue by mahmoudmy** [TiagoDanin/Nuxt-SEO#70]
Hello,
On my site when I go to new page meta tags doesn't update, but when I press F5, It's OK!

**Comment by TiagoDanin** [comment]
I can't reproduce this problem. Could describe how to reproduce

**Comment by mahmoudmy** [comment]
Check it here: [rondoit.com](https://rondoit.com)
For example click on navbar links you see that title doesn't change, but if you refresh that page (F5) it's OK!

**Comment by SeverinAlexB** [comment]
I encounter the same problem. The title doesn't change on client-side navigation.
In order to make this work, `nuxt-seo` needs to subscribe to route changes with a [Nuxt middleware](https://nuxtjs.org/guides/directory-structure/middleware).

#69 fixed that the title is set at all but this issue is still open.

Short code snippets to reproduce:

```js
// nuxt.config.js

export default {
  seo: {
      name: "My Application",
      title: "Index",
      templateTitle: "%title% - %name%"
  }
}

```

```js
// pages/index.vue

export default {
  asyncData: function(ctx) {
    ctx.seo({
      title: 'Index',
    })
  }
}
```

```js
// pages/about.vue

export default {
  asyncData: function(ctx) {
    ctx.seo({
      title: 'About',
    })
  }
}
```

Navigating from `/` to `/about` with `nuxt-link` will not result in a title change.

------

Versions
- nuxt-seo: 1.4.0
- nuxt: 2.14.6

**Comment by TiagoDanin** [comment]
When SSR is enabled, and new page is open via `nuxt-link`, vue-meta (`Vue.prototype.$meta`) return `undefined`. Fix this in 1.4.1 
https://github.com/TiagoDanin/Nuxt-SEO/releases/tag/v1.4.1

Update package to 1.4.1 and replace:

```js
asyncData: function(ctx) {
			ctx.seo({
				name: 'Name app',
				title: 'Home Page',
				templateTitle: '%name% - %title%',
				description: 'Hello World Page'
			})
		}
```

to 

```js
head: function() {
			return this.$seo({
				name: 'Name app',
				title: 'Home Page',
				templateTitle: '%name% - %title%',
				description: 'Hello World Page'
			})
		}
```

Doc update! https://github.com/TiagoDanin/Nuxt-SEO#nuxt-head-context

**Comment by TiagoDanin** [comment]
@mahmoudmy Only confirm that it has been fixed :)

**Comment by mahmoudmy** [comment]
Every thing is fine, thanks a lot 👍

**Comment by SeverinAlexB** [comment]
Great! That fix took way less code than I thought. Works like a charm.
