### ISSUE TITLE
No favicon

### ISSUE THREAD

**Issue by enterinit** [TiagoDanin/Nuxt-SEO#78]
Hi. With this module Nuxt doesn't recognize favicon that I'm set in "<head />" in nuxt.config.js. And there is no module options to set favicon. Any suggestions?

**Comment by SeverinAlexB** [comment]
I am having the same problem. Actually, all `link`'s configured in nuxt.config.js `head` don't work as soon as the nuxt-seo module is activated.

**Comment by SeverinAlexB** [comment]
@TiagoDanin Thanks for merging and releasing a new version :)

**Comment by TiagoDanin** [comment]
https://github.com/TiagoDanin/Nuxt-SEO/releases/tag/v1.4.2

**Comment by TiagoDanin** [comment]
@Sebubu thanks again
