### ISSUE TITLE
Make canonical URL trailing slash optional

### ISSUE THREAD

**Issue by ceilfors** [TiagoDanin/Nuxt-SEO#86]
**Is your feature request related to a problem? Please describe.**
Version 1.4.x introduces canonical URL, but it forces trailing slash at the back of the URL making the upgrade a breaking change. This should not be enforced.

**Describe the solution you'd like**
Make trailing slash enforcement optional.

**Additional context**
- Nuxt-SEO version 1.4.x.

P.S. Thank you @TiagoDanin for maintaining this module, it has saved us a lot of time making meta tags work in Nuxt! :)

**Comment by TiagoDanin** [comment]
Done in version [1.5.0](https://github.com/TiagoDanin/Nuxt-SEO/releases/tag/v1.5.0).
Add new option [`isForcedTrailingSlash`](https://github.com/TiagoDanin/Nuxt-SEO#isforcedtrailingslash), default is disable in 1.5.0

**Comment by ceilfors** [comment]
Wow! That's fantastic and super speedy! @TiagoDanin 🤩
